# Generated by Django 3.1 on 2022-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_logcustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcustomgroup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
