# Generated by Django 3.1 on 2022-03-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0006_logorderdetail_purchase_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logsaledetail',
            name='packing_type',
        ),
        migrations.RemoveField(
            model_name='logsaledetail',
            name='packing_type_detail',
        ),
    ]
