# Generated by Django 3.1 on 2022-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0007_auto_20220314_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='logorderdetail',
            name='picked',
            field=models.BooleanField(default=False, help_text='order picked from warehouse'),
        ),
    ]
