# Generated by Django 3.1 on 2022-03-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220215_1257'),
        ('log_app', '0008_logorderdetail_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='logorderdetail',
            name='item_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='item.itemcategory'),
        ),
    ]
