# Generated by Django 3.1 on 2022-04-01 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0013_auto_20220401_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='logassetlist',
            name='warranty_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
