# Generated by Django 3.1 on 2022-04-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0016_logassetlist_end_of_life'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logassetlist',
            name='end_of_life',
        ),
        migrations.AddField(
            model_name='logassetlist',
            name='end_of_life_in_years',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
