# Generated by Django 3.1 on 2022-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0017_auto_20220403_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='logordermaster',
            name='pick_verified',
            field=models.BooleanField(default=False, help_text='Customer order id picked from ware house'),
        ),
    ]
