# Generated by Django 3.1 on 2022-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0019_logchalandetail_logchalanmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logchalanmaster',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'CHALAN'), (2, 'BILLED'), (3, 'RETURNED')], help_text='Where 1 = CHALAN, 2 = BILLED,  3 = RETURNED, Default=1'),
        ),
        migrations.AlterField(
            model_name='logordermaster',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'BILLED'), (3, 'CANCELLED'), (4, 'CHALAN')], help_text='Where 1 = PENDING, 2 = BILLED,  3 = CANCELLED, 4 = CHALAN Default=1'),
        ),
    ]
