# Generated by Django 3.2 on 2022-05-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0023_auto_20220418_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logcountry',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='logcountry',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='logcountry',
            name='currency_symbol',
        ),
    ]
