# Generated by Django 3.2 on 2022-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0025_logcurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='basic_info',
            field=models.CharField(blank=True, help_text='Basic info can be max. of 50 characters', max_length=255, null=True),
        ),
    ]
