# Generated by Django 3.2 on 2022-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0028_logitem_harmonic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logpurchasemaster',
            name='country_currency',
        ),
        migrations.RemoveField(
            model_name='logpurchaseordermaster',
            name='country_currency',
        ),
    ]
