# Generated by Django 3.2 on 2022-05-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0029_auto_20220509_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loguser',
            name='full_name',
            field=models.CharField(blank=True, help_text='full name max length=152', max_length=152),
        ),
    ]
