# Generated by Django 3.2 on 2022-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0031_auto_20220524_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchaseordermaster',
            name='attendee',
            field=models.CharField(blank=True, help_text='Name of Attendee max = 150', max_length=150, null=True),
        ),
    ]
