# Generated by Django 3.2 on 2022-05-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0034_logpurchaseorderdetail_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchaseorderdetail',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
