# Generated by Django 3.2 on 2022-06-03 05:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0039_auto_20220527_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchaseorderdetail',
            name='sale_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
