# Generated by Django 3.2 on 2022-06-12 10:00

from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0041_auto_20220612_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='favicon',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[src.core_app.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='signature',
            field=models.TextField(blank=True, help_text='signature image of organization owner', max_length=100, null=True, validators=[src.core_app.models.validate_image]),
        ),
    ]
