# Generated by Django 3.2 on 2022-06-13 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
        ('log_app', '0043_logquotationdetail_logquotationmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='logquotationdetail',
            name='quotation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='quotation.quotationmaster'),
        ),
    ]
