# Generated by Django 3.2 on 2022-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0044_logquotationdetail_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='logquotationdetail',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
