# Generated by Django 3.2 on 2022-07-01 06:37

import django.core.validators
from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0048_logordermaster_by_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='logo',
            field=models.TextField(blank=True, max_length=100, validators=[src.core_app.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
