# Generated by Django 3.2 on 2022-07-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0049_alter_logorganizationsetup_logo'),
        ('log_app', '0049_auto_20220701_1053'),
    ]

    operations = [
    ]
