# Generated by Django 3.2 on 2022-07-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0050_merge_20220704_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcreditpaymentdetail',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment Mode ID, Esewa No/Khalti No/Cheque No', max_length=255),
        ),
        migrations.AddField(
            model_name='logpartypaymentdetail',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment Mode ID, Esewa No/Khalti No/Cheque No', max_length=255),
        ),
        migrations.AddField(
            model_name='logpurchasepaymentdetail',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment Mode ID, Esewa No/Khalti No/Cheque No', max_length=255),
        ),
        migrations.AddField(
            model_name='logsalepaymentdetail',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment Mode ID, Esewa No/Khalti No/Cheque No', max_length=255),
        ),
    ]
