# Generated by Django 3.2 on 2022-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0051_auto_20220707_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchasedetail',
            name='batch_no',
            field=models.CharField(help_text='Batch no. max length 20', max_length=15),
        ),
    ]
