# Generated by Django 3.2 on 2022-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0052_alter_logpurchasedetail_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchasedetail',
            name='batch_no',
            field=models.CharField(help_text='Batch no. max length 20', max_length=20),
        ),
    ]
