# Generated by Django 3.2 on 2022-07-15 04:35

from django.db import migrations, models
import src.core_app.models
import src.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0054_auto_20220714_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='signature',
            field=models.TextField(blank=True, default='default_images/signature.png', help_text='signature image of organization owner', max_length=100, null=True, validators=[src.core_app.models.validate_organization_setup_images]),
        ),
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='stamp',
            field=models.TextField(blank=True, default='default_images/stamp.png', help_text='stamp image of organization', max_length=100, validators=[src.core_app.models.validate_organization_setup_images]),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='photo',
            field=models.TextField(blank=True, default='default_images/profile.png', max_length=100, validators=[src.user.models.validate_image]),
        ),
    ]
