# Generated by Django 3.2 on 2022-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0055_auto_20220715_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='signature',
            field=models.TextField(blank=True, default='default_images/signature.png', help_text='signature image of organization owner', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logorganizationsetup',
            name='stamp',
            field=models.TextField(blank=True, default='default_images/stamp.png', help_text='stamp image of organization', max_length=100),
        ),
    ]
