# Generated by Django 3.2 on 2022-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0058_logordermaster_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcurrency',
            name='name',
            field=models.CharField(db_index=True, help_text='currency_name can be have max upto 50 characters and null=True, blank=True', max_length=50),
        ),
    ]
