# Generated by Django 3.2 on 2022-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0060_logtransferdetail_logtransfermaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpurchasedetail',
            name='ref_transfer_detail',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
