# Generated by Django 3.2 on 2022-10-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_auto_20221030_1552'),
        ('log_app', '0061_logpurchasedetail_ref_transfer_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransferdetail',
            name='ref_transfer_order_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transfer.transferorderdetail'),
        ),
        migrations.AddField(
            model_name='logtransfermaster',
            name='ref_transfer_order_master',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transfer.transferordermaster'),
        ),
    ]
