# Generated by Django 3.2 on 2022-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0062_auto_20221030_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransferdetail',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logtransfermaster',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
