# Generated by Django 3.2 on 2022-11-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0065_logtransfermaster_is_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtransfermaster',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
