# Generated by Django 3.2 on 2022-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0066_logtransfermaster_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logassetlist',
            name='amc_rate',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='available',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='depreciation_method',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='end_of_life_in_years',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='maintenance_duration',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='salvage_value',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='scrapped',
        ),
        migrations.RemoveField(
            model_name='logassetlist',
            name='warranty_duration',
        ),
        migrations.AlterField(
            model_name='logtransfermaster',
            name='branch',
            field=models.PositiveIntegerField(),
        ),
    ]
