# Generated by Django 3.2 on 2022-11-13 05:35

from django.db import migrations, models
import src.item.models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0067_auto_20221113_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='image',
            field=models.TextField(blank=True, default='default_images/product.png', max_length=100, validators=[src.item.models.validate_image]),
        ),
    ]
