# Generated by Django 3.2 on 2022-11-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0068_alter_logitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='logpaymentmode',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'CASH'), (2, 'BANK'), (3, 'WALLET')], default=1),
        ),
    ]
