# Generated by Django 3.2 on 2022-11-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_assetlist_asset'),
        ('log_app', '0068_logasset_logassetcategory_logassetsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='logassetlist',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.asset'),
        ),
    ]
