# Generated by Django 3.2 on 2022-11-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0069_logassetlist_asset'),
        ('log_app', '0069_logpaymentmode_type'),
    ]

    operations = [
    ]
