# Generated by Django 3.2 on 2022-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0070_merge_20221127_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logassetlist',
            name='remarks',
        ),
        migrations.AddField(
            model_name='logasset',
            name='registration_no',
            field=models.CharField(blank=True, db_index=True, help_text='registration no. should be max. of 10 characters', max_length=20),
        ),
    ]
