# Generated by Django 3.2 on 2022-12-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log_app', '0071_auto_20221127_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='logordermaster',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logordermaster',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
