# Generated by Django 3.2 on 2022-12-05 10:16

from django.db import migrations, models
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0073_logorderdetail_picked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcustomer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
    ]
