# Generated by Django 3.2 on 2022-12-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_location', '0001_initial'),
        ('log_app', '0076_alter_logordermaster_credit_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='logasset',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='warehouse_location.location'),
        ),
    ]
