# Generated by Django 3.2 on 2022-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0076_alter_logordermaster_credit_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logorderdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
