# Generated by Django 3.2 on 2022-12-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0077_alter_logorderdetail_remarks'),
        ('log_app', '0078_auto_20221219_1414'),
    ]

    operations = [
    ]
