# Generated by Django 3.2 on 2022-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0080_logassetdispatch_logassetdispatchdetail_logassetmaintenance_logassettransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logassetdispatch',
            name='dispatch_sub_type',
            field=models.CharField(choices=[(1, 'MAINTENANCE'), (2, 'TRANSFER')], help_text='Dispatch Sub Type choices, max of 15 characters', max_length=15, null=True),
        ),
    ]
