# Generated by Django 3.2 on 2022-05-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_harmonic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='basic_info',
            field=models.TextField(blank=True, help_text='Basic info can text field', null=True),
        ),
    ]
