# Generated by Django 3.2 on 2022-11-13 05:35

from django.db import migrations, models
import src.item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default_images/product.png', upload_to='item', validators=[src.item.models.validate_image]),
        ),
    ]
