# Generated by Django 3.2 on 2022-05-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20220215_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='currency_symbol',
        ),
    ]
