# Generated by Django 3.2 on 2022-06-12 07:07

from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_currency_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsetup',
            name='signature',
            field=models.ImageField(blank=True, help_text='signature image of organization owner', upload_to='organization_setup/signature', validators=[src.core_app.models.validate_image]),
        ),
        migrations.AddField(
            model_name='organizationsetup',
            name='stamp',
            field=models.ImageField(blank=True, help_text='stamp image of organization', upload_to='organization_setup/stamp', validators=[src.core_app.models.validate_image]),
        ),
    ]
