# Generated by Django 3.2 on 2022-07-01 06:37

import django.core.validators
from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_auto_20220612_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetup',
            name='logo',
            field=models.ImageField(blank=True, upload_to='organization_setup/logo', validators=[src.core_app.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
