# Generated by Django 3.2 on 2022-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_auto_20220715_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetup',
            name='signature',
            field=models.ImageField(blank=True, default='default_images/signature.png', help_text='signature image of organization owner', null=True, upload_to='organization_setup/signature'),
        ),
        migrations.AlterField(
            model_name='organizationsetup',
            name='stamp',
            field=models.ImageField(blank=True, default='default_images/stamp.png', help_text='stamp image of organization', upload_to='organization_setup/stamp'),
        ),
    ]
