# Generated by Django 3.2 on 2022-07-22 05:11

import django.core.validators
from django.db import migrations, models
import src.core_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_auto_20220722_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsetup',
            name='favicon',
            field=models.ImageField(blank=True, default='default_images/favicon.ico', null=True, upload_to='organization_setup/favicon', validators=[src.core_app.models.validate_organization_setup_images]),
        ),
        migrations.AlterField(
            model_name='organizationsetup',
            name='logo',
            field=models.ImageField(blank=True, default='default_images/soori.png', upload_to='organization_setup/logo', validators=[src.core_app.models.validate_organization_setup_images, django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AlterField(
            model_name='organizationsetup',
            name='signature',
            field=models.ImageField(blank=True, default='default_images/signature.png', help_text='signature image of organization owner', null=True, upload_to='organization_setup/signature', validators=[src.core_app.models.validate_organization_setup_images]),
        ),
        migrations.AlterField(
            model_name='organizationsetup',
            name='stamp',
            field=models.ImageField(blank=True, default='default_images/stamp.png', help_text='stamp image of organization', upload_to='organization_setup/stamp', validators=[src.core_app.models.validate_organization_setup_images]),
        ),
    ]
