# Generated by Django 3.2 on 2022-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_auto_20220722_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='currency_name can be have max upto 50 characters and null=True, blank=True', max_length=50, unique=True),
        ),
    ]
