# Generated by Django 3.2 on 2022-07-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0002_customgroup_remarks'),
        ('user', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='user_group.CustomGroup'),
        ),
    ]
