# Generated by Django 3.1 on 2022-03-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20220215_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetail',
            name='packing_type',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='packing_type_detail',
        ),
    ]
