# Generated by Django 3.1 on 2022-04-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0002_auto_20220413_1655'),
        ('sale', '0003_auto_20220314_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='ref_chalan_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chalan.chalandetail'),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='ref_chalan_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chalan.chalanmaster'),
        ),
    ]
