# Generated by Django 3.1 on 2022-04-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20220330_1425'),
        ('sale', '0004_auto_20220417_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='purchase.purchasedetail'),
        ),
    ]
