# Generated by Django 3.2 on 2022-07-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20220418_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemaster',
            name='return_dropped',
            field=models.BooleanField(default=True, help_text='True if items are dropped to locations after returning'),
        ),
    ]
