# Generated by Django 3.2 on 2022-11-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accountgroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='type',
            field=models.IntegerField(choices=[(1, 'ASSET'), (2, 'INCOME'), (3, 'EXPENSES')]),
        ),
    ]
