# Generated by Django 3.2 on 2022-11-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accountgroup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroup',
            name='type',
        ),
    ]
