# Generated by Django 3.2 on 2022-11-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_accountgroup_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchermaster',
            old_name='invoice_no',
            new_name='voucher_no',
        ),
    ]
