# Generated by Django 3.2 on 2022-11-27 06:17

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20221127_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.accountgroup'),
        ),
    ]
