# Generated by Django 3.2 on 2022-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_accountgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermaster',
            name='reference',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
