# Generated by Django 3.2 on 2022-11-28 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_vouchermaster_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermaster',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 5, 58, 15, 631889, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
