# Generated by Django 3.2 on 2022-11-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_vouchermaster_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermaster',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
