# Generated by Django 3.2 on 2022-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermaster',
            name='type',
            field=models.CharField(choices=[('JOURNAL', 'Journal Voucher'), ('SALE', 'Sale Voucher'), ('PURCHASE', 'Purchase Voucher'), ('SUPPLIER', 'Supplier Payment Voucher'), ('CUSTOMER', 'Customer Payment Voucher'), ('PURCHASE-RETURN', 'Purchase Return Voucher'), ('SALE-RETURN', 'Sales Return Voucher')], default='JOURNAL', max_length=100),
        ),
    ]
