# Generated by Django 3.2 on 2022-12-07 05:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetail',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
