# Generated by Django 3.2 on 2022-09-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermaster',
            name='branch',
            field=models.PositiveIntegerField(),
        ),
    ]
