# Generated by Django 3.2 on 2022-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotationdetail_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmaster',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
