# Generated by Django 3.2 on 2022-06-15 04:43

from django.db import migrations, models
import src.custom_lib.functions.field_value_validation


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotationmaster_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetail',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12, validators=[src.custom_lib.functions.field_value_validation.gt_zero_validator]),
        ),
    ]
