# Generated by Django 3.1 on 2022-04-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20220330_1425'),
        ('chalan', '0003_chalanmaster_discount_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chalandetail',
            old_name='order_detail',
            new_name='ref_order_detail',
        ),
        migrations.RenameField(
            model_name='chalanmaster',
            old_name='order_master',
            new_name='ref_order_master',
        ),
        migrations.AddField(
            model_name='chalandetail',
            name='ref_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasedetail'),
        ),
    ]
