# Generated by Django 3.2 on 2022-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='created_date_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
