# Generated by Django 3.1 on 2022-02-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_serialization', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='sale_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.saledetail', verbose_name='Sale Detail'),
        ),
    ]
