# Generated by Django 3.1 on 2022-02-27 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20220227_1029'),
        ('item_serialization', '0003_auto_20220215_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingtypecode',
            name='purchase_order_detail',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='po_pack_type_codes', to='purchase.purchaseorderdetail', verbose_name='Purchase Order Detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packingtypecode',
            name='purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pu_pack_type_codes', to='purchase.purchasedetail', verbose_name='Purchase Detail'),
        ),
    ]
