# Generated by Django 3.1 on 2022-03-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20220215_1257'),
        ('customer_order', '0002_auto_20220215_1257'),
        ('item_serialization', '0004_auto_20220227_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='customer_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_order.orderdetail', verbose_name='Customer order detail'),
        ),
        migrations.AlterField(
            model_name='salepackingtypecode',
            name='sale_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.saledetail', verbose_name='Sale Detail'),
        ),
    ]
