# Generated by Django 3.1 on 2022-03-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0006_auto_20220307_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='ref_sale_packing_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.salepackingtypecode'),
        ),
        migrations.AddField(
            model_name='salepackingtypedetailcode',
            name='ref_sale_packing_type_detail_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.salepackingtypedetailcode'),
        ),
    ]
