# Generated by Django 3.1 on 2022-03-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0008_auto_20220310_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingtypecode',
            name='code',
            field=models.CharField(help_text='max-20', max_length=20, verbose_name='Packing Type Serial No'),
        ),
        migrations.AlterField(
            model_name='packingtypedetailcode',
            name='code',
            field=models.CharField(help_text='max-20', max_length=20, verbose_name='Packing Type Detail Serail No'),
        ),
    ]
