# Generated by Django 3.1 on 2022-03-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0003_orderdetail_purchase_detail'),
        ('item_serialization', '0009_auto_20220310_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepackingtypecode',
            name='customer_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_packing_types', to='customer_order.orderdetail', verbose_name='Customer order detail'),
        ),
    ]
