# Generated by Django 3.1 on 2022-03-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20220314_1512'),
        ('item_serialization', '0010_auto_20220313_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepackingtypecode',
            name='sale_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_packing_type_code', to='sale.saledetail', verbose_name='Sale Detail'),
        ),
    ]
