# Generated by Django 3.1 on 2022-04-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20220314_1512'),
        ('warehouse_location', '0001_initial'),
        ('chalan', '__first__'),
        ('item_serialization', '0011_auto_20220320_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChalanPackingTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_type_code', to='chalan.chalandetail')),
            ],
        ),
        migrations.AlterField(
            model_name='packingtypecode',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='location_pack_codes', to='warehouse_location.location', verbose_name='Pack Type Location'),
        ),
        migrations.AlterField(
            model_name='salepackingtypecode',
            name='packing_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_type_code_of_sale', to='item_serialization.packingtypecode', verbose_name='sale packing type code'),
        ),
        migrations.AlterField(
            model_name='salepackingtypecode',
            name='sale_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_packing_type_code', to='sale.saledetail', verbose_name='Sale Detail'),
        ),
        migrations.AlterField(
            model_name='salepackingtypedetailcode',
            name='packing_type_detail_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_type_detail_code_of_sale', to='item_serialization.packingtypedetailcode'),
        ),
        migrations.AlterField(
            model_name='salepackingtypedetailcode',
            name='sale_packing_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_packing_type_detail_code', to='item_serialization.salepackingtypecode'),
        ),
        migrations.CreateModel(
            name='ChalanPackingTypeDetailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalan_packing_type_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_type_detail_code', to='item_serialization.chalanpackingtypecode')),
                ('packing_type_detail_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chalan_packing_type_detail_code', to='item_serialization.packingtypedetailcode')),
                ('ref_chalan_packing_type_detail_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.chalanpackingtypedetailcode')),
            ],
        ),
        migrations.AddField(
            model_name='chalanpackingtypecode',
            name='packing_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chalan_packing_type_code', to='item_serialization.packingtypecode', verbose_name='sale packing type code'),
        ),
        migrations.AddField(
            model_name='chalanpackingtypecode',
            name='ref_chalan_packing_type_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_serialization.chalanpackingtypecode'),
        ),
    ]
