# Generated by Django 3.1 on 2022-04-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0012_auto_20220413_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalanpackingtypedetailcode',
            name='ref_chalan_packing_type_detail_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_ref', to='item_serialization.chalanpackingtypedetailcode'),
        ),
    ]
