# Generated by Django 3.1 on 2022-04-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0013_auto_20220413_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalanpackingtypecode',
            name='ref_chalan_packing_type_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_serialization.chalanpackingtypecode'),
        ),
    ]
