# Generated by Django 3.2 on 2022-04-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0014_auto_20220417_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chalanpackingtypedetailcode',
            name='chalan_packing_type_code',
        ),
        migrations.RemoveField(
            model_name='chalanpackingtypedetailcode',
            name='packing_type_detail_code',
        ),
        migrations.RemoveField(
            model_name='chalanpackingtypedetailcode',
            name='ref_chalan_packing_type_detail_code',
        ),
        migrations.DeleteModel(
            name='ChalanPackingTypeCode',
        ),
        migrations.DeleteModel(
            name='ChalanPackingTypeDetailCode',
        ),
    ]
