# Generated by Django 3.2 on 2022-04-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chalan', '0004_auto_20220418_1541'),
        ('item_serialization', '0015_auto_20220425_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepackingtypecode',
            name='chalan_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chalan_packing_types', to='chalan.chalandetail', verbose_name='Chalan Detail'),
        ),
    ]
