# Generated by Django 3.2 on 2022-12-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0018_rfidtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidtag',
            name='code',
            field=models.CharField(help_text='max-20', max_length=20, unique=True, verbose_name='Packing Type Detail Serial No'),
        ),
        migrations.AlterField(
            model_name='rfidtag',
            name='pack_type_detail_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_tag_codes', to='item_serialization.packingtypedetailcode', verbose_name='Rfid Tag Code'),
        ),
    ]
