# Generated by Django 3.2 on 2022-12-16 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0019_auto_20221215_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidtag',
            name='last_seen_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfidtag',
            name='code',
            field=models.CharField(help_text='max-20', max_length=255, unique=True, verbose_name='Packing Type Detail Serial No'),
        ),
    ]
