# Generated by Django 3.2 on 2022-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0020_auto_20221216_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidtag',
            name='code',
            field=models.CharField(help_text='max-20', max_length=255, unique=True, verbose_name='Rfid Tag Key Code'),
        ),
    ]
