# Generated by Django 3.2 on 2022-06-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_alter_purchaseorderdetail_sale_cost'),
        ('party_payment', '0002_auto_20220215_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partypayment',
            name='purchase_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_payments', to='purchase.purchasemaster'),
        ),
    ]
