# Generated by Django 3.1 on 2022-02-15 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item_serialization', '0002_salepackingtypecode_sale_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetservice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetlist',
            name='packing_type_detail_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='item_serialization.packingtypedetailcode'),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.assetlist'),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_issued_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetissue',
            name='return_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_return_received_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
