# Generated by Django 3.2 on 2022-11-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20220403_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlist',
            name='amc_rate',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='available',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='depreciation_method',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='end_of_life_in_years',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='maintenance_duration',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='salvage_value',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='scrapped',
        ),
        migrations.RemoveField(
            model_name='assetlist',
            name='warranty_duration',
        ),
    ]
