# Generated by Django 3.2 on 2022-11-09 07:44

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0005_alter_item_basic_info'),
        ('asset', '0008_auto_20221109_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True, help_text='By default=true')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True, help_text='By default=true')),
                ('asset_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('scrapped', models.BooleanField(default=False, help_text='default = False')),
                ('available', models.BooleanField(default=True, help_text='default = True')),
                ('qty', models.PositiveIntegerField(help_text='no of assets')),
                ('adjusted_book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters', max_length=100)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='value of asset after its full use', max_digits=7)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate of Depreciation', max_digits=4)),
                ('amc_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual Maintenance Charge Rate', max_digits=4)),
                ('depreciation_method', models.IntegerField(choices=[(1, 'STRAIGHT-LINE'), (2, 'DECLINING-BALANCE')], default=1, help_text='deprecation method : 1 = STRAIGHT-LINE, 2 = DECLINING-BALANCE, default value is = 1')),
                ('end_of_life_in_years', models.PositiveIntegerField(default=1)),
                ('warranty_duration', models.DurationField(default=datetime.timedelta(0))),
                ('maintenance_duration', models.DurationField(default=datetime.timedelta(0))),
                ('bulk_update', models.BooleanField(default=False, help_text='By default=false')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.assetsubcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
