# Generated by Django 3.2 on 2022-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_assetlist_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlist',
            name='remarks',
        ),
        migrations.AddField(
            model_name='asset',
            name='registration_no',
            field=models.CharField(blank=True, help_text='registration no. should be max. of 10 characters', max_length=20, unique=True),
        ),
    ]
