# Generated by Django 3.2 on 2022-12-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_location', '0001_initial'),
        ('asset', '0012_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_location', to='warehouse_location.location'),
        ),
    ]
