# Generated by Django 3.2 on 2022-12-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_location', '0001_initial'),
        ('asset', '0013_alter_asset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AddField(
            model_name='assetlist',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_location', to='warehouse_location.location'),
        ),
    ]
