# Generated by Django 3.2 on 2022-12-20 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0014_auto_20221219_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('receiver_name', models.CharField(help_text='Name of the receiver, can be of max 200 characters', max_length=200)),
                ('receiver_id_no', models.CharField(blank=True, help_text='Receiver Id No of the user', max_length=50)),
                ('dispatch_no', models.CharField(help_text='Dispatch No, can be of max. 20 characters', max_length=20, unique=True)),
                ('dispatch_type', models.CharField(choices=[(1, 'INTERNAL'), (2, 'EXTERNAL')], help_text='Dispatch type choices max of 10 characters', max_length=10)),
                ('dispatch_info', models.CharField(choices=[(1, 'DISPATCH'), (2, 'RETURN')], help_text='Dispatch info choices max of 10 characters', max_length=10)),
                ('dispatch_sub_type', models.CharField(choices=[(1, 'MAINTENANCE'), (1, 'TRANSFER')], help_text='Dispatch Sub Type choices, max of 15 characters', max_length=15, null=True)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters and blank=True', max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispatch_by', models.ForeignKey(help_text='dispatch by user', on_delete=django.db.models.deletion.PROTECT, related_name='asset_dispatch_by', to=settings.AUTH_USER_MODEL)),
                ('dispatch_to', models.ForeignKey(help_text='dispatch to user', on_delete=django.db.models.deletion.PROTECT, related_name='asset_dispatch_to', to=settings.AUTH_USER_MODEL)),
                ('ref_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ref_asset_dispatch', to='asset.assetdispatch')),
                ('returned_by', models.ForeignKey(help_text='Returned by user', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_dispatch_return_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('transfer_no', models.CharField(help_text='Asset Transfer no, can have max of 20 characters', max_length=20, unique=True)),
                ('remarks', models.CharField(blank=True, help_text='Remarks should be max. of 100 characters and blank=True', max_length=100)),
                ('asset_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_transfer', to='asset.assetdispatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('maintenance_no', models.CharField(help_text='Asset Repair no, can have max of 20 characters', max_length=20, unique=True)),
                ('next_maintenance_date', models.DateField()),
                ('issue_reasons', models.TextField(blank=True)),
                ('expected_return_date', models.DateField()),
                ('asset_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance', to='asset.assetdispatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_maintenance_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDispatchDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('asset_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_dispatch_asset', to='asset.assetlist')),
                ('asset_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_dispatches', to='asset.assetdispatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ref_dispatch_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ref_asset_dispatch_detail', to='asset.assetdispatchdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
