# Generated by Django 3.1 on 2022-02-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20220227_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarehouseLocation',
        ),
    ]
