# Generated by Django 3.1 on 2022-03-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20220308_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='batch_no',
            field=models.CharField(help_text='Batch no. max length 20', max_length=8),
        ),
    ]
