# Generated by Django 3.1 on 2022-03-30 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220215_1257'),
        ('purchase', '0007_auto_20220327_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='purchase.purchasemaster'),
        ),
    ]
