# Generated by Django 3.1 on 2022-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20220330_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='pay_type',
            field=models.PositiveIntegerField(choices=[(1, 'CASH'), (2, 'CREDIT')], help_text='Pay type like CASH, CREDIT'),
        ),
    ]
