# Generated by Django 3.2 on 2022-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20220330_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasemaster',
            name='country_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseordermaster',
            name='country_currency',
        ),
    ]
