# Generated by Django 3.2 on 2022-05-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20220509_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchaseordermaster'),
        ),
    ]
