# Generated by Django 3.2 on 2022-05-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_alter_purchaseordermaster_ref_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermaster',
            name='ref_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_purchase_order_master', to='purchase.purchaseordermaster'),
        ),
    ]
