# Generated by Django 3.2 on 2022-05-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_alter_purchaseordermaster_ref_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermaster',
            name='attendee',
            field=models.CharField(blank=True, help_text='Name of Attendee max = 150', max_length=150, null=True),
        ),
    ]
