# Generated by Django 3.2 on 2022-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_purchaseordermaster_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermaster',
            name='attendee',
            field=models.CharField(blank=True, default='', help_text='Name of Attendee max = 150', max_length=150),
            preserve_default=False,
        ),
    ]
