# Generated by Django 3.2 on 2022-05-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_auto_20220527_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderdetail',
            name='ref_purchase_order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_purchase_order_detail', to='purchase.purchaseorderdetail'),
        ),
    ]
