# Generated by Django 3.2 on 2022-07-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_purchasepaymentdetail_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='batch_no',
            field=models.CharField(help_text='Batch no. max length 20', max_length=15),
        ),
    ]
