# Generated by Django 3.2 on 2022-07-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_alter_purchasedetail_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='batch_no',
            field=models.CharField(help_text='Batch no. max length 20', max_length=20),
        ),
    ]
