# Generated by Django 3.2 on 2022-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_alter_purchasedetail_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='ref_transfer_detail',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
