# Generated by Django 3.1 on 2022-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
