# Generated by Django 3.2 on 2022-06-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_address'),
        ('customer', '0003_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIsSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_is_supplier', to='customer.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_is_customer', to='supplier.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'customer')},
            },
        ),
    ]
