# Generated by Django 3.1 on 2022-03-10 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20220310_1532'),
        ('customer_order', '0002_auto_20220215_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchasedetail'),
        ),
    ]
