# Generated by Django 3.1 on 2022-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0003_orderdetail_purchase_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='picked',
            field=models.BooleanField(default=False, help_text='order picked from warehouse'),
        ),
    ]
