# Generated by Django 3.1 on 2022-03-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20220215_1257'),
        ('customer_order', '0004_orderdetail_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.itemcategory'),
        ),
    ]
