# Generated by Django 3.1 on 2022-04-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0005_orderdetail_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='pick_verified',
            field=models.BooleanField(default=False, help_text='Customer order id picked from ware house'),
        ),
    ]
