# Generated by Django 3.1 on 2022-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_ordermaster_pick_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'PENDING'), (2, 'BILLED'), (3, 'CANCELLED'), (4, 'CHALAN')], help_text='Where 1 = PENDING, 2 = BILLED,  3 = CANCELLED, 4 = CHALAN Default=1'),
        ),
    ]
