# Generated by Django 3.2 on 2022-08-07 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_order', '0008_ordermaster_by_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
