# Generated by Django 3.2 on 2022-12-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_order', '0009_ordermaster_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermaster',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
