# Generated by Django 3.2 on 2022-12-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0011_orderdetail_picked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='credit_term',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
    ]
