# Generated by Django 3.2 on 2022-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0013_alter_ordermaster_credit_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
