# Generated by Django 3.2 on 2022-06-12 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20220418_1541'),
        ('credit_management', '0002_auto_20220215_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditclearance',
            name='sale_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_clearance', to='sale.salemaster'),
        ),
    ]
