# Generated by Django 3.1 on 2022-03-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='packing_type_detail_code',
        ),
    ]
