# Generated by Django 3.1 on 2022-03-06 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_serialization', '0005_auto_20220302_1501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0002_remove_audit_packing_type_detail_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=10)),
                ('device_type', models.PositiveBigIntegerField(choices=[(1, 'Mobile'), (2, 'PC'), (3, 'Tablet'), (4, 'Other'), (5, 'NA')], default=5, help_text='where 1=Mobile, 2=PC, 3=Tablet and 4=Other')),
                ('app_type', models.PositiveBigIntegerField(choices=[(1, 'Web-App'), (2, 'IOS-App'), (3, 'Android-App'), (4, 'NA')], default=4, help_text='where 1=Web-App, 2=IOS-APP, 3=Android-APP')),
                ('detail_type', models.IntegerField(choices=[(1, 'AVAILABLE'), (2, 'AUDITED'), (3, 'MISSING')])),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_details', to='audit.audit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('packing_type_detail_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_serialization.packingtypedetailcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
